on: [push]
name: CI

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          code:
            - '**.rs'
            - '**.c'
    - if: steps.changes.outputs.code == 'true'
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
    - uses: actions-rs/cargo@v1
      if: steps.changes.outputs.code == 'true'
      with:
        toolchain: nightly
        command: build
        args: --release --all-features
    - name: Archive production artifacts
      if: steps.changes.outputs.code == 'true'
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: |
          target/release/rget
          target/release/rail
