on: [push]
name: CI

jobs:
  build:
    name: Rustutil
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --all-features
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: |
          target/release/rget
          target/release/rail
