on: [push]
name: CI

jobs:
  check-for-changes:
    runs-on: ubuntu-latest
    outputs:
      server: ${{ steps.filter.outputs.code }}
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          code:
            - '**.rs'
            - '**.c'

  build:
    name: Build
    needs: check-for-changes
    runs-on: ubuntu-latest
    if: ${{ needs.check-for-changes.outputs.code == 'true' }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
    - uses: actions-rs/cargo@v1
      with:
        toolchain: nightly
        command: build
        args: --release --all-features
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: |
          target/release/rget
          target/release/rail
